### ISSUE TITLE
installing PyGEL3D

### ISSUE THREAD

**Issue by mariloubodde** [malariagen/anospp-analysis#14]
Just some notes so I can check back later. 

When I initially installed PyGEL3D I did `pip install pygel3d` which back then installed version `0.2.1`. When I did the same today to install PyGEL3D into a new environment, it installed version `0.3.2`, which resulted in an error when I tried to import the library. The problem was that the later version builds a `C++` library for MacOS 12.3, whereas my machine is still on 11.7.6. 

The solution was to install the specific version using `pip install pygel3d==0.2.1`.

**Comment by amakunin** [comment]
OK, this means [my initial attempt to create pygel3d conda-forge recipe](https://github.com/conda-forge/staged-recipes/pull/22561) from wheel that contains pre-compiled libraries should not be moved forward. I will still try to create recipe that both compiles c++ code and installs python bindings, but no guarantees here

**Comment by amakunin** [comment]
Closing as this dependency was removed
