### ISSUE TITLE
Issue with blast mis-classifying haplotypes

### ISSUE THREAD

**Issue by jorels1** [malariagen/anospp-analysis#23]
There is a current issue where after blast-driven haplotype classification, two sequences which has one sequence difference, here at the first nucleotide are erroneously classified as the same haplotype but the reads are not merged.

Proposed fix is to include the option of considering the query cover stats in grouping haplotypes rather than solely percent identity.

Will fix once I am back from holidays.

**Comment by amakunin** [comment]
Closing as fixed by #22
